### ISSUE TITLE
Set up subgraph to collect data

### ISSUE THREAD

**Issue by ryanycw** [AlibudaLab/atomic-indexer#1]
1. Set up subgraph to collect following collection

    * [x] Get All Challenges
    * [x] Get Challenge Detail by Id
    * [x] Get All User Joined Challenges
    * [x] Get User Checkin Counts

2. Adjust fe to integrate the new subgraph

**Comment by antoncoding** [comment]
* [x] get all challenges => participants for each challenge

**Comment by ryanycw** [comment]
Closed with #2
